version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Instalar las dependencias de Python
      - pip install -U pytest
  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
      - pytest
